# Generated by Django 5.1.5 on 2025-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
