# Generated by Django 5.1.5 on 2025-02-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
