# Generated by Django 5.1.5 on 2025-02-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='decision',
            field=models.CharField(choices=[('NE', 'Not Earned'), ('TB', 'TBD'), ('EA', 'Earned'), ('UD', 'Undecided')], default='UD', max_length=50),
        ),
    ]
