# Generated by Django 5.1.5 on 2025-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submission_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='decision',
            field=models.CharField(choices=[('NE', 'Not Earned'), ('TB', 'TBD'), ('EA', 'Earned'), ('UN', 'Undecided')], default='UN', max_length=50),
        ),
    ]
