# Generated by Django 5.1.5 on 2025-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_submission_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='decision',
            field=models.CharField(choices=[('NE', 'Not Earned'), ('TB', 'TBD'), ('EA', 'Earned')], default='TB', max_length=50),
        ),
    ]
